# Site settings
title: Desarrollo Web ... entre otras cosas
description: Desarrollo Web ... entre otras cosas
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.yagoperez.com" # the base hostname & protocol for your site

# User settings
name: Yago Pérez Vázquez
username: Yago Pérez
user_description: Frontend developer
user_title:  Desarrollo Web ... entre otras cosas
email: yagoperez@outlook.com
twitter_username: yperezva
github_username:  yagopv
gplus_username:  yawette
disqus_username: yagopv

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: Portfolio
    url: /portfolio

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

# Pagination settings
paginate: 10
paginate_path: "/page/:num/"

gems: [jekyll-paginate]